import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function Navbar() {
    return (
        <nav className="bg-[#2e026d] text-white">
        <div className="container mx-auto flex items-center justify-between h-16">
        <div className="flex items-center">
        <a href="/" className="text-xl font-bold">
        Tuitions
        </a>
        </div>
        <div className="flex items-center space-x-4">
        <a href="/classes" className="text-sm font-bold">
        Classes
        </a>
        <a href="/students" className="text-sm font-bold">
        Students
        </a>
        </div>
        </div>
        </nav>
    );
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={`${GeistSans.variable}`}>
        <body>
        <Navbar />
        {children}
        </body>
        </html>
    );
}
